FROM jenkins/inbound-agent:4.11-1-jdk8



USER root



# Build and release pipelines to run apt-get,

# apt does not require confirmation (assume the -y argument by default)

ENV DEBIAN_FRONTEND=noninteractive

RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes



# Update and Upgrade Debian Buster 10

RUN apt-get update \

  && apt-get upgrade -y --no-install-recommends 



# Install Dependencies

RUN apt-get update \

  && apt-get install -y --no-install-recommends \

        apt-transport-https \

        ca-certificates \

        curl \

        gnupg-agent \

        jq \

        iputils-ping \

        netcat \

        wget \

        unzip \

        tree \

        vim \

        git



# GCC and CPP Installation

RUN apt-get install -y --no-install-recommends \

        build-essential \

        software-properties-common \

        libc6-dev \

        gcc \

        g++\

        cpp \

        dpkg-dev \

        make \

        cmake



# Python3 Installation

RUN apt-get install -y --no-install-recommends \

        python3 \

        python3-dev \

        python3-pip \

        virtualenv \

        libssl-dev \

        libffi-dev 



# Python3 Flask Installation

RUN pip3 install flask 



# NodeJS 14 LTS Installation

WORKDIR /home/jenkins/nodejs

RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -

RUN apt-get update

RUN apt-get install -y --no-install-recommends nodejs



# Maven 3.8.3 Installation

RUN apt-get install -y --no-install-recommends maven

WORKDIR /home/jenkins/maven

RUN wget https://dlcdn.apache.org/maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz

RUN tar -xvzf apache-maven-3.8.3-bin.tar.gz \

  && mv apache-maven-3.8.3 maven \

  && mv /usr/share/maven /usr/share/maven-old \ 

  && mv maven /usr/share/

RUN rm -rf /home/jenkins/maven/apache-maven-3.8.3-bin.tar.gz



# Install Docker CLI on Debian

# Add Docker’s official GPG key:

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

# Set up the stable repo

RUN echo \

  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \

  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

# Update the apt package index, and install the latest version of Docker Engine and Container, or go to the next step to install a specific version:

RUN apt-get update && apt-get install -y docker-ce-cli



# Cleanup Debian Environment

RUN rm -rf /var/lib/apt/lists/*

RUN apt-get autoremove -y && apt-get autoclean -y && apt-get clean -y



# Start Jenkins Agent

USER jenkins



ENTRYPOINT ["/usr/local/bin/jenkins-agent"]
